version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ca-central-1"
    REPOSITORY_URI: "445567079138.dkr.ecr.ca-central-1.amazonaws.com/khanam-final-ecr"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo Logging into $REPOSITORY_URI
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest    # ✅ ADD THIS

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest                               # ✅ ADD THIS
      - echo "Creating imagedefinitions.json..."
      - |
        echo '[ 
          { 
            "name": "khanam-final-ecr", 
            "imageUri": "'$REPOSITORY_URI:$IMAGE_TAG'" 
          } 
        ]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
